// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRDjNAvFE_INfcidbvIc-lcLqMSH7FPiM',
    appId: '1:225851575136:web:9aa87b624028abec3cac05',
    messagingSenderId: '225851575136',
    projectId: 'restaurantapp123',
    authDomain: 'restaurantapp123-63069.firebaseapp.com',
    storageBucket: 'restaurantapp123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALvLQyodmpG_KSjIjkk-y3Mpr-lvjxK2A',
    appId: '1:225851575136:android:763bc63b6f3c72683cac05',
    messagingSenderId: '225851575136',
    projectId: 'restaurantapp123',
    storageBucket: 'restaurantapp123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_FtIE8qzvziHcx_Mtux6dzwiwqDDmtSA',
    appId: '1:225851575136:ios:9871da2bf98ce9373cac05',
    messagingSenderId: '225851575136',
    projectId: 'restaurantapp123',
    storageBucket: 'restaurantapp123.firebasestorage.app',
    iosBundleId: 'com.example.restaurantmobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_FtIE8qzvziHcx_Mtux6dzwiwqDDmtSA',
    appId: '1:225851575136:ios:9871da2bf98ce9373cac05',
    messagingSenderId: '225851575136',
    projectId: 'restaurantapp123',
    storageBucket: 'restaurantapp123.firebasestorage.app',
    iosBundleId: 'com.example.restaurantmobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRDjNAvFE_INfcidbvIc-lcLqMSH7FPiM',
    appId: '1:225851575136:web:fbde9b2c35f75dc93cac05',
    messagingSenderId: '225851575136',
    projectId: 'restaurantapp123',
    authDomain: 'restaurantapp123-63069.firebaseapp.com',
    storageBucket: 'restaurantapp123.firebasestorage.app',
  );
}
